'use client';

import React, { createContext, useContext, useState } from 'react';

export const LANGUAGES = ['English', 'Hindi', 'Spanish', 'Japanese', 'Latin', 'Arabic', 'Russian', 'Cosmic/Mixed'];

type Translations = Record<string, Record<string, string>>;

const translations: Translations = {
  English: {
    summon: "Summon The Dark Verses",
    command: "Command Mr. Kilvish to write your next anthem. Choose your genre and set the mood.",
    selectLanguage: "Select Language",
    selectGenre: "Select Genre",
    themes: "Themes & Keywords",
    generate: "Generate Anthem",
    channeling: "Channeling...",
    title: "Title",
    style: "Style",
    lyrics: "Lyrics",
    manifest: "Your anthem will manifest here",
    generatingMedia: "Manifesting Cover Art & Audio...",
    coverArt: "Cover Art",
    audioPreview: "Audio Preview",
    masteringLab: "Mastering Lab",
    masteringDesc: "Transform your raw tracks into professional anthems with Kilvish AI.",
    uploadTrack: "Upload MP3 Track",
    processTrack: "Master My Track",
    processing: "Mastering in Progress...",
    downloadMastered: "Download Mastered Track",
    bassBoost: "Void Bass",
    clarity: "Cosmic Clarity",
    loudness: "Empire Volume",
    musicStudio: "Kilvish Studio",
    studioDesc: "The ultimate multiversal workstation. Compose, mix, and dominate.",
    addTrack: "Add Track",
    piano: "Void Piano",
    drums: "Dark Drums",
    bass: "Deep Bass",
    volume: "Vol",
    pan: "Pan",
    play: "Play",
    stop: "Stop",
    navMusic: "Music",
    navFilms: "Films",
    navLegacy: "Legacy",
    heroDominating: "The World Dominating",
    heroDesc: "Artist. Producer. Director. Music Songwriter. The One And Only.",
    heroLatest: "Latest Release",
    heroFilmography: "View Filmography",
    domainArtist: "Artist",
    domainArtistDesc: "Vocal dominance across genres",
    domainProducer: "Producer",
    domainProducerDesc: "Sonic architect of the dark",
    domainDirector: "Director",
    domainDirectorDesc: "Visualizing the unseen",
    domainSongwriter: "Songwriter",
    domainSongwriterDesc: "Penning the eternal anthems",
    filmographyTitle: "Filmography",
    filmographyDesc: "The visual manifestations of darkness",
    role: "Role",
    year: "Year",
    synopsis: "Synopsis",
  },
  Hindi: {
    summon: "डार्क वर्सेज का आह्वान करें",
    command: "मिस्टर किल्विश को अपना अगला एंथम लिखने का आदेश दें। अपनी शैली चुनें और मूड सेट करें।",
    selectLanguage: "भाषा चुनें",
    selectGenre: "शैली चुनें",
    themes: "विषय और कीवर्ड",
    generate: "एंथम बनाएं",
    channeling: "चैनलिंग...",
    title: "शीर्षक",
    style: "शैली",
    lyrics: "बोल",
    manifest: "आपका एंथम यहाँ प्रकट होगा",
    generatingMedia: "कवर आर्ट और ऑडियो बना रहे हैं...",
    coverArt: "कवर आर्ट",
    audioPreview: "ऑडियो पूर्वावलोकन",
    masteringLab: "मास्टरिंग लैब",
    masteringDesc: "किलविश एआई के साथ अपने गानों को प्रोफेशनल एंथम में बदलें।",
    uploadTrack: "MP3 ट्रैक अपलोड करें",
    processTrack: "मेरा ट्रैक मास्टर करें",
    processing: "मास्टरिंग चल रही है...",
    downloadMastered: "मास्टर किया हुआ ट्रैक डाउनलोड करें",
    bassBoost: "वॉयड बास",
    clarity: "कॉस्मिक क्लैरिटी",
    loudness: "एम्पायर वॉल्यूम",
    musicStudio: "किलविश स्टूडियो",
    studioDesc: "परम बहुमुखी वर्कस्टेशन। रचना करें, मिक्स करें और राज करें।",
    addTrack: "ट्रैक जोड़ें",
    piano: "वॉयड पियानो",
    drums: "डार्क ड्रम",
    bass: "डीप बास",
    volume: "वॉल्यूम",
    pan: "पैन",
    play: "प्ले",
    stop: "स्टॉप",
    navMusic: "संगीत",
    navFilms: "फिल्में",
    navLegacy: "विरासत",
    heroDominating: "विश्व पर हावी",
    heroDesc: "कलाकार। निर्माता। निर्देशक। संगीत गीतकार। एक और केवल।",
    heroLatest: "नवीनतम रिलीज़",
    heroFilmography: "फिल्मोग्राफी देखें",
    domainArtist: "कलाकार",
    domainArtistDesc: "शैलियों में मुखर प्रभुत्व",
    domainProducer: "निर्माता",
    domainProducerDesc: "अंधेरे के ध्वनि वास्तुकार",
    domainDirector: "निर्देशक",
    domainDirectorDesc: "अदृश्य की कल्पना",
    domainSongwriter: "गीतकार",
    domainSongwriterDesc: "शाश्वत एंथम लिखना",
    filmographyTitle: "फिल्मोग्राफी",
    filmographyDesc: "अंधेरे की दृश्य अभिव्यक्तियाँ",
    role: "भूमيكا",
    year: "वर्ष",
    synopsis: "सारांश",
  },
  Spanish: {
    summon: "Invoca Los Versos Oscuros",
    command: "Ordena al Sr. Kilvish que escriba tu próximo himno. Elige tu género y establece el estado de ánimo.",
    selectLanguage: "Seleccionar Idioma",
    selectGenre: "Seleccionar Género",
    themes: "Temas y Palabras Clave",
    generate: "Generar Himno",
    channeling: "Canalizando...",
    title: "Título",
    style: "Estilo",
    lyrics: "Letras",
    manifest: "Tu himno se manifestará aquí",
    navMusic: "Música",
    navFilms: "Películas",
    navLegacy: "Legado",
    heroDominating: "Dominando el Mundo",
    heroDesc: "Artista. Productor. Director. Compositor. El Único.",
    heroLatest: "Último Lanzamiento",
    heroFilmography: "Ver Filmografía",
    domainArtist: "Artista",
    domainArtistDesc: "Dominio vocal en todos los géneros",
    domainProducer: "Productor",
    domainProducerDesc: "Arquitecto sónico de la oscuridad",
    domainDirector: "Director",
    domainDirectorDesc: "Visualizando lo invisible",
    domainSongwriter: "Compositor",
    domainSongwriterDesc: "Escribiendo los himnos eternos",
    filmographyTitle: "Filmografía",
    filmographyDesc: "Las manifestaciones visuales de la oscuridad",
    role: "Papel",
    year: "Año",
    synopsis: "Sinopsis",
  },
  Japanese: {
    summon: "闇の詩を召喚する",
    command: "キルヴィッシュ氏に次のアンセムを書くよう命じます。ジャンルを選び、ムードを設定してください。",
    selectLanguage: "言語を選択",
    selectGenre: "ジャンルを選択",
    themes: "テーマとキーワード",
    generate: "アンセムを生成",
    channeling: "チャネリング中...",
    title: "タイトル",
    style: "スタイル",
    lyrics: "歌詞",
    manifest: "あなたのアンセムがここに現れます",
    navMusic: "音楽",
    navFilms: "映画",
    navLegacy: "レガシー",
    heroDominating: "世界を支配する",
    heroDesc: "アーティスト。プロデューサー。監督。ソングライター。唯一無二。",
    heroLatest: "最新リリース",
    heroFilmography: "フィルモグラフィーを見る",
    domainArtist: "アーティスト",
    domainArtistDesc: "ジャンルを超えたボーカルの支配",
    domainProducer: "プロデューサー",
    domainProducerDesc: "闇の音響建築家",
    domainDirector: "監督",
    domainDirectorDesc: "見えざるものの視覚化",
    domainSongwriter: "ソングライター",
    domainSongwriterDesc: "永遠のアンセムを執筆",
    filmographyTitle: "フィルモグラフィー",
    filmographyDesc: "闇の視覚的顕現",
    role: "役割",
    year: "年",
    synopsis: "あらすじ",
  },
  Latin: {
    summon: "Invoca Versus Obscuros",
    command: "Iube Dominum Kilvish scribere hymnum tuum. Elige genus et animum.",
    selectLanguage: "Elige Linguam",
    selectGenre: "Elige Genus",
    themes: "Argumenta et Verba",
    generate: "Genera Hymnum",
    channeling: "Invocans...",
    title: "Titulus",
    style: "Stilus",
    lyrics: "Litterae",
    manifest: "Hymnus tuus hic manifestabitur",
    navMusic: "Musica",
    navFilms: "Pelliculae",
    navLegacy: "Hereditas",
    heroDominating: "Mundum Dominans",
    heroDesc: "Artifex. Productor. Director. Scriptor. Unicus.",
    heroLatest: "Ultima Editio",
    heroFilmography: "Vide Pelliculas",
    domainArtist: "Artifex",
    domainArtistDesc: "Dominatio vocalis per genera",
    domainProducer: "Productor",
    domainProducerDesc: "Architectus sonicus tenebrarum",
    domainDirector: "Director",
    domainDirectorDesc: "Videns invisibilia",
    domainSongwriter: "Scriptor",
    domainSongwriterDesc: "Scribens hymnos aeternos",
    filmographyTitle: "Pelliculae",
    filmographyDesc: "Manifestationes visuales tenebrarum",
    role: "Persona",
    year: "Annus",
    synopsis: "Synopsis",
  },
  Arabic: {
    summon: "استدعاء الآيات المظلمة",
    command: "أمر السيد كيلفيش بكتابة نشيدك التالي. اختر نوعك وحدد المزاج.",
    selectLanguage: "اختر اللغة",
    selectGenre: "اختر النوع",
    themes: "المواضيع والكلمات الرئيسية",
    generate: "توليد النشيد",
    channeling: "توجيه...",
    title: "العنوان",
    style: "الأسلوب",
    lyrics: "كلمات",
    manifest: "سيظهر نشيدك هنا",
    navMusic: "موسيقى",
    navFilms: "أفلام",
    navLegacy: "إرث",
    heroDominating: "المهيمن على العالم",
    heroDesc: "فنان. منتج. مخرج. كاتب أغاني. الوحيد.",
    heroLatest: "أحدث إصدار",
    heroFilmography: "عرض قائمة الأفلام",
    domainArtist: "فنان",
    domainArtistDesc: "هيمنة صوتية عبر الأنواع",
    domainProducer: "منتج",
    domainProducerDesc: "مهندس صوتي للظلام",
    domainDirector: "مخرج",
    domainDirectorDesc: "تصور غير المرئي",
    domainSongwriter: "كاتب أغاني",
    domainSongwriterDesc: "كتابة الأناشيد الأبدية",
    filmographyTitle: "قائمة الأفلام",
    filmographyDesc: "المظاهر البصرية للظلام",
    role: "دور",
    year: "عام",
    synopsis: "ملخص",
  },
  Russian: {
    summon: "Призыв Темных Стихов",
    command: "Прикажите мистеру Килвишу написать ваш следующий гимн. Выберите жанр и задайте настроение.",
    selectLanguage: "Выберите язык",
    selectGenre: "Выберите жанр",
    themes: "Темы и ключевые слова",
    generate: "Создать гимн",
    channeling: "Направление...",
    title: "Название",
    style: "Стиль",
    lyrics: "Текст",
    manifest: "Ваш гимн появится здесь",
    navMusic: "Музыка",
    navFilms: "Фильмы",
    navLegacy: "Наследие",
    heroDominating: "Доминирующий в мире",
    heroDesc: "Художник. Продюсер. Режиссер. Автор песен. Единственный.",
    heroLatest: "Последний релиз",
    heroFilmography: "Смотреть фильмографию",
    domainArtist: "Художник",
    domainArtistDesc: "Вокальное доминирование во всех жанрах",
    domainProducer: "Продюсер",
    domainProducerDesc: "Звуковой архитектор тьмы",
    domainDirector: "Режиссер",
    domainDirectorDesc: "Визуализация невидимого",
    domainSongwriter: "Автор песен",
    domainSongwriterDesc: "Написание вечных гимнов",
    filmographyTitle: "Фильмография",
    filmographyDesc: "Визуальные проявления тьмы",
    role: "Роль",
    year: "Год",
    synopsis: "Синопсис",
  },
  'Cosmic/Mixed': {
    summon: "⟒⋔⟟⏁ ⏁⊑⟒ ⎐⍜⟟⎅ (Summon The Dark Verses)",
    command: "☊⍜⋔⋔⏃⋏⎅ ⏁⊑⟒ ⟒⋏⏁⟟⏁⊬ (Command Mr. Kilvish)",
    selectLanguage: "⌇⟒⌰⟒☊⏁ ⏁⍜⋏☌⎍⟒ (Select Language)",
    selectGenre: "⌇⟒⌰⟒☊⏁ ⎎⍜⍀⋔ (Select Genre)",
    themes: "⏁⊑⍜⎍☌⊑⏁⌇ (Themes & Keywords)",
    generate: "⋔⏃⋏⟟⎎⟒⌇⏁ (Generate Anthem)",
    channeling: "☊⊑⏃⋏⋏⟒⌰⟟⋏☌... (Channeling...)",
    title: "⋏⏃⋔⟒ (Title)",
    style: "⎎⍜⍀⋔ (Style)",
    lyrics: "⎐⟒⍀⌇⟒⌇ (Lyrics)",
    manifest: "⏁⊑⟒ ⎐⍜⟟⎅ ⏃⍙⏃⟟⏁⌇ (Your anthem will manifest here)",
    generatingMedia: "⋔⏃⋏⟟⎎⟒⌇⏁⟟⋏☌ ⎐⟟⌇⟟⍜⋏⌇... (Manifesting Cover Art & Audio...)",
    coverArt: "⎐⟟⌇⟟⍜⋏ (Cover Art)",
    audioPreview: "⎐⍜⟟☊⟒ (Audio Preview)",
    masteringLab: "⋔⏃⌇⏁⟒⍀⟟⋏☌ ⌰⏃⏚",
    masteringDesc: "⏁⍀⏃⋏⌇⎎⍜⍀⋔ ⊬⍜⎍⍀ ⌇⍜⎍⋏☌⌇ ⟟⋏⏁⍜ ⎐⍜⟟☊⟒⌇...",
    uploadTrack: "⎍⌿⌰⍜⏃⎅ ⌇⍜⎍⋏☌",
    processTrack: "⋔⏃⌇⏁⟒⍀ ⋔⊬ ⌇⍜⎍⋏☌",
    processing: "⋔⏃⌇⏁⟒⍀⟟⋏☌ ⟟⋏ ⎐⍜⟟⎅...",
    downloadMastered: "⎅⍜⍙⋏⌰⍜⏃⎅ ⋔⏃⌇⏁⟒⍀",
    bassBoost: "⎐⍜⟟⎅ ⏚⏃⌇⌇",
    clarity: "☊⌰⏃⍀⟟⏁⊬",
    loudness: "⎐⍜⌰⎍⋔⟒",
    musicStudio: "☍⟟⌰⎐⟟⌇⊑ ⌇⏁⎍⎅⟟⍜",
    studioDesc: "⏁⊑⟒ ⎐⍜⟟⎅ ⍙⍜⍀☍⌇⏁⏃⏁⟟⍜⋏...",
    addTrack: "⏃⎅⎅ ⏁⍀⏃☊☍",
    piano: "⎐⍜⟟⎅ ⌿⟟⏃⋏⍜",
    drums: "⎅⏃⍀☍ ⎅⍀⎍⋔⌇",
    bass: "⎅⟒⟒⌿ ⏚⏃⌇⌇",
    volume: "⎐⍜⌰",
    pan: "⌿⏃⋏",
    play: "⌿⌰⏃⊬",
    stop: "⌇⏁⍜⌿",
    navMusic: "⋔⎍⌇⟟☊",
    navFilms: "⎎⟟⌰⋔⌇",
    navLegacy: "⌰⟒☌⏃☊⊬",
    heroDominating: "☊⍜⌇⋔⟟☊ ⎅⍜⋔⟟⋏⏃⏁⟟⍜⋏",
    heroDesc: "⟒⋏⏁⟟⏁⊬. ☊⍀⟒⏃⏁⍜⍀. ⎅⟒⌇⏁⍀⍜⊬⟒⍀.",
    heroLatest: "⋏⟒⍙ ⎐⟟⏚⍀⏃⏁⟟⍜⋏",
    heroFilmography: "⎐⟟⌇⟟⍜⋏⌇",
    domainArtist: "⟒⋏⏁⟟⏁⊬ (Entity)",
    domainArtistDesc: "Universal resonance",
    domainProducer: "⏃⍀☊⊑⟟⏁⟒☊⏁ (Architect)",
    domainProducerDesc: "Shaper of reality",
    domainDirector: "⎐⟟⌇⟟⍜⋏⏃⍀⊬ (Visionary)",
    domainDirectorDesc: "Seer of the void",
    domainSongwriter: "⌇☊⍀⟟⏚⟒ (Scribe)",
    domainSongwriterDesc: "Writer of the cosmos",
    filmographyTitle: "⎐⟟⌇⟟⍜⋏⌇ (Filmography)",
    filmographyDesc: "⋔⏃⋏⟟⎎⟒⌇⏁⏃⏁⟟⍜⋏⌇ ⍜⎎ ⏁⊑⟒ ⎐⍜⟟⎅ (Visual manifestations of the void)",
    role: "⎎⍜⍀⋔ (Form)",
    year: "☊⊬☊⌰⟒ (Cycle)",
    synopsis: "⏁⍀⎍⏁⊑ (Truth)",
  }
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState(LANGUAGES[0]);

  const t = (key: string) => {
    return translations[language]?.[key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
