export const GENRES = [
  'Auto',
  'Pop', 'Rock', 'Hip-Hop', 'Electronic', 'Classical', 'Dark Ambient',
  'Jazz', 'Blues', 'R&B', 'Soul', 'Country', 'Folk', 'Reggae', 'Metal', 'Punk',
  'Indie', 'Alternative', 'Dance', 'House', 'Techno', 'Trance', 'Dubstep',
  'Drum and Bass', 'Ambient', 'Synthwave', 'Vaporwave', 'Lo-Fi', 'Trap',
  'Drill', 'Grime', 'Afrobeats', 'Dancehall', 'Reggaeton', 'Latin', 'Salsa',
  'Bachata', 'Cumbia', 'K-Pop', 'J-Pop', 'Gospel', 'Christian', 'Opera',
  'Musical Theatre', 'Soundtrack', 'Score', 'Acoustic', 'Unplugged', 'Live',
  'Experimental', 'Avant-Garde', 'Noise', 'Industrial', 'Goth', 'Emo',
  'Screamo', 'Post-Hardcore', 'Metalcore', 'Death Metal', 'Black Metal',
  'Doom Metal', 'Sludge Metal', 'Stoner Rock', 'Psychedelic Rock', 'Prog Rock',
  'Math Rock', 'Shoegaze', 'Dream Pop', 'Post-Punk', 'New Wave', 'Synth-Pop',
  'Disco', 'Funk', 'Boogie', 'Electro', 'Freestyle', 'Miami Bass', 'Bounce',
  'Crunk', 'Snap', 'Hyphy', 'Mumble Rap', 'Conscious Hip-Hop', 'Boom Bap',
  'Jazz Rap', 'G-Funk', 'Horrorcore',  'Hyperpop', 'Slap House', 'Brazilian Funk', 'Detroit Techno', 'Hard Techno', 'Industrial Techno', 'Melodic Techno', 'Psytrance', 'Stutter House', 'Phonk (Viral)', 'Drill (Viral)', 'Amapiano (Viral)', 'Afrobeats (Viral)', 'K-Pop (Viral)', 'Phonk', 'Cloud Rap', 'Emo Rap',
  'Epic Battle', 'Cinematic Dialogue', 'Heroic Anthem', 'Dark Orchestral', 'Battle Rap', 'Dramatic Score',
  'Pop Punk', 'Skate Punk', 'Ska', 'Rockabilly', 'Psychobilly', 'Surf Rock',
  'Garage Rock', 'Grunge', 'Britpop', 'Madchester', 'Trip-Hop', 'Big Beat',
  'Breakbeat', 'UK Garage', '2-Step', 'Bassline', 'Dub', 'Roots Reggae',
  'Lovers Rock', 'Ska Punk', 'Celtic', 'Bluegrass', 'Americana', 'Outlaw Country',
  'Bro-Country', 'Honky Tonk', 'Western Swing', 'Rocksteady', 'Calypso',
  'Soca', 'Zouk', 'Kizomba', 'Highlife', 'Juju', 'Afrobeat', 'Kwaito',
  'Amapiano', 'Gqom', 'Bongo Flava', 'Coupe Decale', 'Soukous', 'Makossa',
  'Mbalax', 'Rai', 'Chaabi', 'Gnawa', 'Qawwali', 'Ghazal', 'Bhangra',
  'Bollywood', 'Carnatic', 'Hindustani', 'Flamenco', 'Fado', 'Tango',
  'Bossa Nova', 'Samba', 'Forro', 'Axé', 'Sertanejo', 'Mariachi',
  'Ranchera', 'Norteño', 'Banda', 'Corridos', 'Cumbia Sonidera',
  'Dembow', 'Champeta', 'Vallenato', 'Merengue', 'Salsa Dura',
  'Salsa Romantica', 'Timba', 'Son Cubano', 'Mambo', 'Cha-Cha-Cha', 'Rumba',
  'Guaguanco', 'Yoruba', 'Santeria', 'Vodou', 'Candomble', 'Macumba',
  'Umbanda', 'Capoeira', 'Samba de Roda', 'Maracatu', 'Frevo', 'Baião',
  'Xote', 'Choro', 'Tropicália', 'MPB', 'Samba-Reggae',
  'Samba-Rock', 'Pagode', 'Funk Carioca', 'Tecnobrega', 'Arrocha', 'Pisadinha',
  'Hardstyle', 'Hardcore', 'Gabber', 'Frenchcore', 'Terrorcore', 'Speedcore',
  'Breakcore', 'Jungle', 'Liquid Drum and Bass', 'Neurofunk', 'Jump-Up',
  'Techstep', 'Darkstep', 'Hardstep', 'Drumstep', 'Half-Step', 'Glitch Hop',
  'IDM', 'Glitch', 'Chiptune', 'Bitpop', 'Nintendocore', 'Cyberpunk',
  'Darksynth', 'Outrun', 'Retrowave', 'Chillwave', 'Gloomcore', 'Witch House',
  'Sea Shanty', 'Barbershop', 'A Cappella', 'Doo-Wop', 'Motown', 'Northern Soul',
  'Neo-Soul', 'Future Bass', 'Kawaii Future Bass', 'Jersey Club', 'Baltimore Club',
  'Vogue', 'Ballroom', 'Kuduro', 'Tarraxinha', 'Ghetto House', 'Ghettotech',
  'Footwork', 'Juke', 'Acid House', 'Acid Techno', 'Acid Jazz', 'Nu Jazz',
  'Electro Swing', 'Gypsy Jazz', 'Klezmer', 'Polka'
];
